### ISSUE TITLE
Dual dialogue?

### ISSUE THREAD

**Issue by smvg** [dimkanovikov/KITScenarist#626] opened 2018-03-25 14:13 UTC
This has probably been suggested before (I can't read Russian so... 😅) but it would be very cool if we could add dual dialogues to our scripts. Other than that, the application is AWESOME. Was about to buy a license for Fade In but I think KITScenarist will do it :)

Keep up the good work!

**Comment by dimkanovikov** [comment] 2018-03-26 05:39
Hi! Yep, we plan to add this feature in the nearest update. Duplicate of the #606

**Closed as completed** 2018-05-08 12:58 UTC
Labels: task, script editor
